version: "3.7"
services:
  app:
    build:
      args:
        user: mmoraisd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: slim
    container_name: slim-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - slim

  db:
    image: mysql:5.7
    container_name: slim-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - slim

  nginx:
    image: nginx:alpine
    container_name: slim-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - slim

networks:
  slim:
    driver: bridge
